# Generated by Django 3.0 on 2020-05-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
